apiVersion: v1
kind: Service

metadata:
  name: react-ros-k8s

spec:
  type: NodePort

  selector:
    app: react-ros-k8s

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31779
